### ISSUE TITLE
Will there be support for WSL2?

### ISSUE THREAD

**Issue by amosbird** [Martin1994/vcxsrv-wsl#2]
WSL2 is going to be generally available in April 2020. Do you have any plan to support it? Or is it already usable? Thanks!

**Comment by Martin1994** [comment]
vcxsrv is a Win32 application. It is independent from WSL. However WSL2 has not support AF_UNIX interop yet so you have to listen a TCP port.

**Comment by amosbird** [comment]
Thanks
